diff -urN aSDIO_WLAN_UART_BT_IW416_16.92.10.p151_16.92.10.p151-FP92-BT-FP92-LINUX-MM5X17241-MGPL/wlan_src/Makefile bSDIO_WLAN_UART_BT_IW416_16.92.10.p151_16.92.10.p151-FP92-BT-FP92-LINUX-MM5X17241-MGPL/wlan_src/Makefile
--- aSDIO_WLAN_UART_BT_IW416_16.92.10.p151_16.92.10.p151-FP92-BT-FP92-LINUX-MM5X17241-MGPL/wlan_src/Makefile	2021-03-26 04:20:05.000000000 -0400
+++ bSDIO_WLAN_UART_BT_IW416_16.92.10.p151_16.92.10.p151-FP92-BT-FP92-LINUX-MM5X17241-MGPL/wlan_src/Makefile	2021-08-23 16:22:28.039842000 -0400
@@ -563,8 +563,8 @@
 	cp -f mlan.$(MODEXT) $(BINDIR)/mlan$(DBG).$(MODEXT)
 
 	cp -f moal.$(MODEXT) $(BINDIR)/moal$(DBG).$(MODEXT)
-	cp -rpf script/load $(BINDIR)/
-	cp -rpf script/unload $(BINDIR)/
+#	cp -rpf script/load $(BINDIR)/
+#	cp -rpf script/unload $(BINDIR)/
 ifeq ($(CONFIG_MUSB),y)
 	cp -rpf script/usbconfig $(BINDIR)/
 endif
@@ -572,7 +572,7 @@
 	cp -f README_MLAN $(BINDIR)
 ifneq ($(APPDIR),)
 	$(MAKE) -C mapp/mlanconfig $@ INSTALLDIR=$(BINDIR)
-	$(MAKE) -C mapp/mlanutl $@ INSTALLDIR=$(BINDIR)
+#	$(MAKE) -C mapp/mlanutl $@ INSTALLDIR=$(BINDIR)
 endif
 
 clean:
